/**
 * POST /upload — Feature I. The one endpoint that moves bytes rather than rows.
 *
 *   body: { token, report_id, upload_id, kind, mime, data_b64 }
 *   →     { ok: true, url, reused }            on success
 *   →     { ok: false, error: '<code>' }       otherwise
 *
 * IDEMPOTENT BY FILENAME. The Drive file is named for the client's upload_id,
 * and an existing file with that name is returned instead of a second copy.
 * This matters more than it looks: the failure this endpoint actually sees in
 * the field is not "the upload failed", it is "the upload succeeded and the
 * response never arrived" — a phone leaving a basement mid-request. The client
 * retries, and without this check the sheet would list the same photo twice.
 *
 * NB report_id is recorded for traceability but NOT validated against the
 * maintenance_reports tab, because it cannot be: drafts never sync, so the
 * report a photo belongs to usually does not exist server-side yet. The photo
 * legitimately arrives before its report.
 *
 * ERROR CODES: the client treats `bad_request`, `too_large` and
 * `unsupported_type` as PERMANENT (retrying cannot help — stop and tell the
 * user) and everything else as retryable. Keep that contract in mind before
 * adding a code.
 *
 * SETUP (one time, in addition to Code.js's steps):
 *   1. Create a Drive folder for the uploads, open it, and copy the id from the
 *      URL (the part after /folders/).
 *   2. Project Settings → Script Properties → PMTS_DRIVE_FOLDER_ID = that id.
 *   3. appsscript.json now requests the Drive scope, so the script must be
 *      RE-AUTHORIZED: run smokeCheck() from the editor once and accept the
 *      prompt, then redeploy in place.
 */

/** Decoded-size ceiling. The app resizes to ~200 KB; anything near this is a
 *  bug on the client, and Apps Script should refuse it rather than time out. */
var MAX_UPLOAD_BYTES = 10 * 1024 * 1024;

var UPLOAD_MIME_EXT = {
  'image/jpeg': 'jpg',
  'image/jpg': 'jpg',
  'image/png': 'png',
};

function handleUpload_(body) {
  var auth = authCaller_(body);
  if (auth.ok !== true) return auth;

  var reportId = String((body && body.report_id) || '').trim();
  var uploadId = String((body && body.upload_id) || '').trim();
  var kind = String((body && body.kind) || '').trim();
  var mime = String((body && body.mime) || '').trim().toLowerCase();
  var dataB64 = (body && body.data_b64) || '';

  if (!uploadId || !reportId) return { ok: false, error: 'bad_request', message: 'missing report_id or upload_id' };
  if (kind !== 'photo' && kind !== 'signature') return { ok: false, error: 'bad_request', message: 'bad kind' };
  if (!UPLOAD_MIME_EXT[mime]) return { ok: false, error: 'unsupported_type', message: mime };
  if (typeof dataB64 !== 'string' || dataB64.length === 0) {
    return { ok: false, error: 'bad_request', message: 'missing data_b64' };
  }
  // Base64 inflates by 4/3; check before decoding so an oversized payload is
  // rejected without allocating it.
  if ((dataB64.length * 3) / 4 > MAX_UPLOAD_BYTES) {
    return { ok: false, error: 'too_large', message: 'file exceeds ' + MAX_UPLOAD_BYTES + ' bytes' };
  }

  // The id is generated by the client and lands in a filename — keep it to
  // characters that cannot confuse a Drive search query.
  if (!/^[A-Za-z0-9._-]{1,64}$/.test(uploadId)) {
    return { ok: false, error: 'bad_request', message: 'bad upload_id' };
  }

  var name = uploadId + '.' + UPLOAD_MIME_EXT[mime];
  var folder = uploadFolder_();

  // Serialized against itself: two devices retrying the same upload_id at once
  // would otherwise both miss the existence check and create two files.
  var lock = LockService.getScriptLock();
  lock.waitLock(30 * 1000);
  try {
    var existing = folder.getFilesByName(name);
    if (existing.hasNext()) {
      return { ok: true, url: existing.next().getUrl(), reused: true };
    }

    var bytes;
    try {
      bytes = Utilities.base64Decode(dataB64);
    } catch (err) {
      return { ok: false, error: 'bad_request', message: 'data_b64 is not valid base64' };
    }
    if (bytes.length > MAX_UPLOAD_BYTES) {
      return { ok: false, error: 'too_large', message: bytes.length + ' bytes' };
    }

    var file = folder.createFile(Utilities.newBlob(bytes, mime, name));
    file.setDescription(
      'PMTS ' + kind + ' · report ' + reportId + ' · uploaded by ' + auth.uid,
    );

    // Link-viewable so the URLs in the sheet are clickable for L2 reviewers.
    // A Workspace policy can forbid link sharing entirely; that must not fail
    // the upload, since the file is already safely stored and reachable by
    // anyone with folder access.
    try {
      file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
    } catch (err) {
      Logger.log('link sharing refused for ' + name + ': ' + err);
    }

    return { ok: true, url: file.getUrl(), reused: false };
  } finally {
    lock.releaseLock();
  }
}

function uploadFolder_() {
  return DriveApp.getFolderById(getRequiredProp_('PMTS_DRIVE_FOLDER_ID'));
}
